#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

    enable_guicolors = true
    colorscheme = "iceberg"
    #colorscheme = "srcery"
    colorscheme_bg = "dark"
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 1
    default_indent = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    filetree_direction = "left"
    filemanager = "defx"
    relativenumber = false
    enable_os_fileformat_icon = false
    checkinstall = false
    search_tools = ["rg", "ag", "pt", "ack", "grep", "findstr"]
    autocomplete_method="coc"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
[[layers]]
    name = "colorscheme"
[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'lang#markdown'
    enableWcwidth = 1
    listItemIndent = 1
[[layers]]
    name = "lang#go"
[[layers]]
    name = 'lang#sh'
    bash-file-head = [
        '#!/usr/bin/env bash',
        '# Time: `strftime("%Y-%m-%d %T")`',
        ''
    ]
[[layers]]
    name = 'lang#toml'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'lang#vim'
[[layers]]
  name = "lang#scala"
[[layers]]
    name = 'format'
[[layers]]
    name = 'git'
[[layers]]
  name = 'tmux'
[[layers]]
  name = "fzf"
[[layers]]
  name = "core#tabline"
  enable = false
[[layers]] 
  name = 'lsp'
  filetypes = [
    'go',
    'scala',
    'sh'
  ]
  [layers.override_cmd]
    go = ['gopls']

[[custom_plugins]]
# name = "gkeep/iceberg-dark"
    name = "cocopon/iceberg.vim"
    merged = false
