#!/usr/bin/env bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
	# Make sure we are using the homebrew in the home directory
	export PATH=${HOME}/homebrew/bin:${PATH}

	git -C "$(brew --repo homebrew/core)" fetch --unshallow || true
	brew update
	brew install coreutils git node repo gnupg neovim golang sqlite zsh unrar \
		telnet python python2 yadm wget findutils htop mediainfo imagemagick \
		gpg2 shellcheck


	if [ -d "$HOME/.iterm2" ]; then
		echo "Setting iTerm preference folder"
		defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
	fi

	if [ -d "$HOME/.config/fonts" ]; then
		for f in "$HOME/.config/fonts/*"; do
			cp -f $f ~/Library/Fonts/
		done
	fi

	echo "Disabling auto-correct"
	defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
	echo "Showing all filename extensions in Finder by default"
	defaults write NSGlobalDomain AppleShowAllExtensions -bool true
	echo "Showing status bar in Finder by default"
	defaults write com.apple.finder ShowStatusBar -bool true
	echo "Avoiding the creation of .DS_Store files on network volumes"
	defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
	echo "Disabling press-and-hold for keys in favor of a key repeat"
	defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

	npm install -g jshint eslint
fi

if [[ "$system_type" == "Linux" ]]; then
	sudo apt-get update
	sudo apt-get install sqlite3 golang-1.10 neovim python-dev python-pip \
		python3-dev python3-pip nfs nfs-common npm shellcheck zsh
	sudo npm install -g jshint eslint
fi

# install npm things

if command -v nvim >/dev/null 2>&1; then
	echo "Bootstraping Vim"
	vim '+PlugInstall' '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

